In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Mathematics
## Linear Algebra
## 1. Transpose

The transpose of a matrix $A$ is denoted as $A^T$.

If $A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$, then its transpose is $A^T = \begin{pmatrix} a & c \\ b & d \end{pmatrix}$.

## Using Numpy

In [2]:
# Import Libraries
import numpy as np
import torch

In [3]:
# create a vector
nv = np.array([ [1, 2, 3, 4] ]) # Row vector

print(nv), print(' ')

# transpose it
print(nv.T), print(' ')

# transpose the transposed!
nvT = nv.T
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [4]:
# Repeat for a Matrix

nM = np.array([ [1, 2, 3, 4],
                [5, 6, 7, 8]
              ])
print(nM), print(' ')

# transpose it
print(nM.T), print(' ')

# transpose the transposed!
nMT = nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]


## Using Pytorch

In [5]:
# create a vector
tv = torch.tensor([ [1, 2, 3, 4] ])

print(tv), print(' ')

# transpose it
print(tv.T), print(' ')

# transpose the transposed!
tvT = tv.T
print(tvT.T)

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])


In [6]:
# create a vector
tM = torch.tensor([ [1, 2, 3, 4],
                    [5, 6, 7, 8]])

print(tM), print(' ')

# transpose it
print(tM.T), print(' ')

# transpose the transposed!
tMT = tM.T
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


## Examine Data Types

In [7]:
print(f'Variable nv of type {type(nv)}')
print(f'Variable nM of type {type(nM)}')
print(f'Variable tv of type {type(tv)}')
print(f'Variable tM of type {type(tM)}')

Variable nv of type <class 'numpy.ndarray'>
Variable nM of type <class 'numpy.ndarray'>
Variable tv of type <class 'torch.Tensor'>
Variable tM of type <class 'torch.Tensor'>


## --- Ends Here ---


## 2. Dot Product

The dot product of two vectors $\mathbf{u}$ and $\mathbf{v}$ is written as $\mathbf{u} \cdot \mathbf{v}$.

It's calculated as the sum of the products of their corresponding components:
$\mathbf{u} \cdot \mathbf{v} = \sum_{i=1}^{n} u_i v_i$

For example, if $\mathbf{u} = [u_1, u_2]$ and $\mathbf{v} = [v_1, v_2]$, then $\mathbf{u} \cdot \mathbf{v} = u_1v_1 + u_2v_2$.

Vectors should have same number of elements

## 📐 Common Linear Algebra Operations

---

### ➕ Vector & Matrix Addition

**Definition:** Elements of the matrices/vectors are added element-wise. The inputs must have the exact same shape.

**Notation:** $\mathbf{A} + \mathbf{B}$ or $\mathbf{u} + \mathbf{v}$

**Example:**
$$
\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} + \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix} = \begin{pmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{pmatrix} = \begin{pmatrix} 6 & 8 \\ 10 & 12 \end{pmatrix}
$$

---

### ✨ Scalar Multiplication

**Definition:** Every element of the vector or matrix is multiplied by a single number (a scalar).

**Notation:** $c\mathbf{A}$ or $c\mathbf{v}$

**Example:**
$$
3 \times \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} = \begin{pmatrix} 3 \times 1 & 3 \times 2 \\ 3 \times 3 & 3 \times 4 \end{pmatrix} = \begin{pmatrix} 3 & 6 \\ 9 & 12 \end{pmatrix}
$$

---

### ✖️ Matrix Multiplication

**Definition:** A more complex operation where the resulting element at row `i`, column `j` is the **dot product** of the `i`-th row of the first matrix and the `j`-th column of the second matrix. For a product $\mathbf{AB}$ to be valid, the number of columns in $\mathbf{A}$ must equal the number of rows in $\mathbf{B}$.

**Notation:** $\mathbf{A}\mathbf{B}$

**Example:**
$$
\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix} = \begin{pmatrix} (1 \cdot 5 + 2 \cdot 7) & (1 \cdot 6 + 2 \cdot 8) \\ (3 \cdot 5 + 4 \cdot 7) & (3 \cdot 6 + 4 \cdot 8) \end{pmatrix} = \begin{pmatrix} 19 & 22 \\ 43 & 50 \end{pmatrix}
$$

---

### ⊙ Element-wise Product (Hadamard Product)

**Definition:** Similar to addition, this operation multiplies elements of two matrices that have the same shape. **This is different from standard matrix multiplication.**

**Notation:** $\mathbf{A} \odot \mathbf{B}$

**Example:**
$$
\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} \odot \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix} = \begin{pmatrix} 1 \cdot 5 & 2 \cdot 6 \\ 3 \cdot 7 & 4 \cdot 8 \end{pmatrix} = \begin{pmatrix} 5 & 12 \\ 21 & 32 \end{pmatrix}
$$

---

### • Dot Product

**Definition:** The sum of the products of the corresponding elements in two vectors of the same length. The result is a single number (a scalar).

**Notation:** $\mathbf{u} \cdot \mathbf{v}$ or $\mathbf{u}^T \mathbf{v}$

**Example:**
$$
\begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix} \cdot \begin{pmatrix} 4 \\ 5 \\ 6 \end{pmatrix} = (1 \times 4) + (2 \times 5) + (3 \times 6) = 4 + 10 + 18 = 32
$$

A Single Number that reflects the commonalities between two objects (vectors, matrices, tensors, signals, images).

The dot product is the computational backbone for many operations:
1. Statistics : Correlation, Least-Squares, Filtering
2. Signal Processing : Fourier Transform, Filtering 
3. Science : Geometry, Physics, Mechanics
4. Linear Algebra : Projection, Transformation, Multiplication
5. Deep Learning : Convolution, Matrix Multiplication. Gram Matrix (Used in Style Transfer)

---

### 📏 Vector Norm (L² Norm)

**Definition:** The length or magnitude of a vector. It's calculated as the square root of the sum of the squares of its elements.

**Notation:** $\|\mathbf{v}\|$ or $\|\mathbf{v}\|_2$

**Example:**
For vector $\mathbf{v} = \begin{pmatrix} 3 \\ 4 \end{pmatrix}$
$$
\|\mathbf{v}\|_2 = \sqrt{3^2 + 4^2} = \sqrt{9 + 16} = \sqrt{25} = 5
$$

---

###  transposed_matrix Transpose

**Definition:** An operation that flips a matrix over its main diagonal. The rows of the original matrix become the columns of the new matrix, and vice-versa.

**Notation:** $\mathbf{A}^T$

**Example:**
$$
\text{If } \mathbf{A} = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix} \text{, then } \mathbf{A}^T = \begin{pmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{pmatrix}
$$

## Using Numpy

In [8]:
# create a vector
nv1 = np.array([1, 2, 3, 4])
nv2 = np.array([0,1,0,-1])

# dot product via function
print(np.dot(nv1, nv2))

# dot product via computation
print(np.sum(nv1*nv2))

-2
-2


## Using Pytorch

In [9]:
# create a vector
tv1 = torch.tensor([1, 2, 3, 4])
tv2 = torch.tensor([0,1,0,-1])

# dot product via function
print(torch.dot(tv1, tv2))

# dot product via computation. Torch even stores individual numbers as tensors.
print(torch.sum(tv1*tv2))

tensor(-2)
tensor(-2)


 ## This is intentionaly kept blank

### Committing Code

In [10]:
!ls -l /kaggle/working/

total 28
---------- 1 root root 25611 Sep 11 08:40 __notebook__.ipynb


In [11]:
# Import necessary libraries
import os
from kaggle_secrets import UserSecretsClient

# 1. AUTHENTICATE
# -----------------
# Get your GitHub credentials from Kaggle Secrets
user_secrets = UserSecretsClient()
github_token = user_secrets.get_secret("GITHUB_TOKEN")
github_user = user_secrets.get_secret("GITHUB_USER")

# 2. SET UP VARIABLES
# ---------------------
# Replace with your repository name and the file you want to commit
repo_name = "Career-Tutorials-and-Certification-Abhilash-Jash"
file_to_commit = "DUDL_Mathematics.ipynb" # IMPORTANT: Change this to your actual file name

# Create a dummy file for this example.
# In your real code, this file should already exist in /kaggle/working/
with open(file_to_commit, "w") as f:
    f.write("This is a test file added from Kaggle.")

# 3. CLONE THE REPOSITORY
# -------------------------
# The URL includes your token for authentication
repo_url = f"https://{github_token}@github.com/{github_user}/{repo_name}.git"
!git clone {repo_url}

# 4. ADD, COMMIT, AND PUSH THE FILE
# -----------------------------------
# Navigate into the cloned repository's directory
%cd {repo_name}

# Configure Git with your user info
!git config --global user.name "{github_user}"
!git config --global user.email "{github_user}@users.noreply.github.com"

# Create the target folder and move the file into it
!mkdir -p A Deep Understanding of Deep Learning
!mv /kaggle/working/{file_to_commit} A Deep Understanding of Deep Learning/

# Add the new file to Git's staging area
!git add A Deep Understanding of Deep Learning/{file_to_commit}

# Commit the changes with a message
!git commit -m "Add {file_to_commit} from Kaggle to A Deep Understanding of Deep Learning folder"

Cloning into 'Career-Tutorials-and-Certification-Abhilash-Jash'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (7/7), 13.65 KiB | 3.41 MiB/s, done.
/kaggle/working/Career-Tutorials-and-Certification-Abhilash-Jash
mv: cannot stat 'Deep': No such file or directory
fatal: pathspec 'A' did not match any files
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Learning/

nothing added to commit but untracked files present (use "git add" to track)


In [12]:
# Push the commit to your GitHub repository
!git push

# 5. CLEANUP
# ----------
# Navigate back to the original directory and remove the cloned repo folder

%cd /kaggle/working/
!rm -rf {repo_name}

print(f"✅ Successfully committed and pushed '{file_to_commit}' to the 'A Deep Understanding of Deep Learning' folder in your repo!")

Everything up-to-date
/kaggle/working
✅ Successfully committed and pushed 'DUDL_Mathematics.ipynb' to the 'A Deep Understanding of Deep Learning' folder in your repo!
